name: data_analysis_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - flake8
  - jupyter
  - jupyterlab
  - ipython
  - pip
  - pandas
  - geopandas
  - seaborn
  - matplotlib
  - geodatasets
  - pip:
      - black
      - nbqa